import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner"
import { isAuthenticated } from "@/lib/actions/auth.action";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const isUserAuthenticated = await isAuthenticated();

  if(!isUserAuthenticated){
    redirect("/sign-in");
  }

  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen bg-background font-sans antialiased" suppressHydrationWarning>
        <div className="relative flex min-h-screen flex-col">
          <Navbar />
          <div className="flex-1">
            <main className="flex-1 py-10">
              <div className="container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {children}
              </div>
            </main>
          </div>
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
